"""add ledger balances

Revision ID: 039d7282fc01
Revises: d0c0ab7c3903
Create Date: 2026-06-11 17:07:35.998267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '039d7282fc01'
down_revision: Union[str, Sequence[str], None] = 'd0c0ab7c3903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('previous_balance', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('tenants', sa.Column('account_balance', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'account_balance')
    op.drop_column('invoices', 'previous_balance')
    # ### end Alembic commands ###
