"""add approved_by and is_recurring to expenses

Revision ID: a0b353b0ca3f
Revises: 1903f9655747
Create Date: 2026-06-02 03:03:56.420075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0b353b0ca3f'
down_revision: Union[str, Sequence[str], None] = '1903f9655747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('approved_by', sa.String(), nullable=True))
    op.add_column('expenses', sa.Column('is_recurring', sa.Boolean(), nullable=True))
    op.drop_column('meter_readings', 'bill_photo_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meter_readings', sa.Column('bill_photo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('expenses', 'is_recurring')
    op.drop_column('expenses', 'approved_by')
    # ### end Alembic commands ###
