"""add status column to expenses for AP tracking

Revision ID: d0c0ab7c3903
Revises: f94a762b0766
Create Date: 2026-06-10 12:47:02.284588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0c0ab7c3903'
down_revision: Union[str, Sequence[str], None] = 'f94a762b0766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'status')
    # ### end Alembic commands ###
