"""add area_sqft and status to units

Revision ID: 1903f9655747
Revises: 477c114cb499
Create Date: 2026-06-01 22:11:11.947452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1903f9655747'
down_revision: Union[str, Sequence[str], None] = '477c114cb499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('area_sqft', sa.Integer(), nullable=True))
    op.add_column('units', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units', 'status')
    op.drop_column('units', 'area_sqft')
    # ### end Alembic commands ###
