"""add line_items json to invoices

Revision ID: f94a762b0766
Revises: a0b353b0ca3f
Create Date: 2026-06-04 07:43:36.161123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f94a762b0766'
down_revision: Union[str, Sequence[str], None] = 'a0b353b0ca3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('line_items', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'line_items')
    # ### end Alembic commands ###
